### ISSUE TITLE
会存在分母是 0 的情况

### ISSUE THREAD

**Issue by Withszm** [kuchiki111/test#1]
把随机生成的数限制在10以内后，会存在分母是 0 的情况
![qq 20170312142108](https://cloud.githubusercontent.com/assets/26157729/23829597/2c819262-0731-11e7-8566-f24fa4c21839.png)

**Comment by kuchiki111** [comment]
![image](https://cloud.githubusercontent.com/assets/24310042/23845924/ca520c90-0805-11e7-912a-4d73c07051e9.png)
已解决整数除法时被除数为0的情况。
解决方法为在除法判断时再对被除数进行一次判断，为0时重新随机整数。
